[project]
name = "bitstack-analytics"
description = "Smart contracts for BitStack Analytics portfolio management"
authors = ["BitStack Team"]
telemetry = false
cache_dir = ".cache"
requirements = []
boot_contracts = []

[contracts.portfolio-tracker]
path = "src/portfolio-tracker.clar"
clarity_version = 2
epoch = "2.4"

[contracts.portfolio-registry]
path = "src/portfolio-registry.clar"
clarity_version = 2
epoch = "2.4"

[[project.requirements]]
contract_id = "SP000000000000000000002Q6VF78.pox-4"

[repl]
costs = true
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
